# Generated by Django 2.2.4 on 2019-09-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Registartion',
            },
        ),
    ]
